version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      my-postgres:
        condition: service_started
  
  my-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypassword
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5