version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      my-postgres:
        condition: service_healthy
  
  my-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypassword
    env_file:
      - .env
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5