# Generated by Django 3.2.25 on 2024-07-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bounty',
            options={'verbose_name_plural': 'bounties'},
        ),
    ]
